image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

before_script:
  - docker login -u "$HEROKU_USER" -p "$HEROKU_PASSWORD" registry.heroku.com
  - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community nodejs-npm
  - npm i -g heroku

deploy-develop:
  stage: deploy
  script:
    - docker run -t -v $PWD:/TruelimeBackend --workdir /TruelimeBackend mcr.microsoft.com/dotnet/core/sdk:2.2 bash -c "dotnet restore && dotnet publish -c Release -o ./bin/Release/PublishOutput"
    - docker build -t registry.heroku.com/api-truelime/web .
    - docker push registry.heroku.com/api-truelime/web
    - heroku container:release web --app api-truelime
  only:
    - master